const $=id=>document.getElementById(id);let busy=false;
function showView(view){const chat=view==='chat';$('chatView').hidden=!chat;$('filesView').hidden=chat;$('pageLabel').textContent=chat?'المحادثة':'ملفات المشروع';document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function message(text,type){const box=document.createElement('div');box.className='message '+type;box.dir='auto';const label=document.createElement('span');label.className='message-label';label.textContent=type==='user'?'أنت':'OMNI NEXUS · تجريبي';box.append(label,document.createTextNode(text));$('messages').append(box);box.scrollIntoView({block:'nearest',behavior:'smooth'});return box}
async function send(){if(busy)return;const question=$('question').value.trim();if(!question)return;busy=true;$('send').disabled=true;$('newChat').disabled=true;$('welcome')?.setAttribute('hidden','');message(question,'user');$('question').value='';const pending=message('جارٍ إعداد الرد…','bot');try{const res=await fetch('/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question}),signal:AbortSignal.timeout(60000)});if(!res.ok)throw Error('HTTP '+res.status);const data=await res.json();pending.remove();message(data.answer||'لم يصل رد من الخادم.','bot');status()}catch(e){pending.remove();message('تعذّر إرسال الرسالة. تأكد من الاتصال وحاول مرة ثانية.','error');$('question').value=question}finally{busy=false;$('send').disabled=false;$('newChat').disabled=false;$('question').focus()}}
$('chatForm').addEventListener('submit',e=>{e.preventDefault();send()});$('question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{$('question').value=b.dataset.prompt;$('question').focus()}));$('newChat').addEventListener('click',()=>{if(busy)return;document.querySelectorAll('.message').forEach(e=>e.remove());$('welcome').hidden=false;$('question').value='';showView('chat');$('question').focus()});
async function status(){try{const r=await fetch('/status',{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error();$('connection').textContent='الخادم متصل';$('connection').classList.add('online')}catch{$('connection').textContent='الخادم غير متاح';$('connection').classList.remove('online')}}
async function files(){try{const res=await fetch('/project/files');if(!res.ok)throw Error();const data=await res.json();$('fileCount').textContent=data.files.length;$('fileList').replaceChildren();for(const file of data.files){const row=document.createElement('div');row.className='file-row';const name=document.createElement('span');name.className='file-name';name.textContent=file.name;const size=document.createElement('span');size.className='file-size';size.textContent=file.size<1024?file.size+' B':(file.size/1024).toFixed(1)+' KB';const link=document.createElement('a');link.href='/project/file/'+file.name.split('/').map(encodeURIComponent).join('/');link.textContent='↓';link.setAttribute('aria-label','تنزيل '+file.name);row.append(name,size,link);$('fileList').append(row)}}catch{$('fileList').textContent='تعذّر تحميل الملفات. أعد تحميل الصفحة للمحاولة مجددًا.'}}
status();files();
